/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/settings/About.vue')['default']
    Appearance: typeof import('./src/components/settings/Appearance.vue')['default']
    ArrayInput: typeof import('./src/components/ArrayInput.vue')['default']
    ArraySelect: typeof import('./src/components/ArraySelect.vue')['default']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownForm: typeof import('bootstrap-vue-next')['BDropdownForm']
    BDropdownGroup: typeof import('bootstrap-vue-next')['BDropdownGroup']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BDropdownItemButton: typeof import('bootstrap-vue-next')['BDropdownItemButton']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    DockerArtefact: typeof import('./src/components/DockerArtefact.vue')['default']
    DockerStats: typeof import('./src/components/DockerStats.vue')['default']
    General: typeof import('./src/components/settings/General.vue')['default']
    HiddenInput: typeof import('./src/components/HiddenInput.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NetworkInput: typeof import('./src/components/NetworkInput.vue')['default']
    ProgressTerminal: typeof import('./src/components/ProgressTerminal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./src/components/settings/Security.vue')['default']
    StackList: typeof import('./src/components/StackList.vue')['default']
    StackListItem: typeof import('./src/components/StackListItem.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    TwoFADialog: typeof import('./src/components/TwoFADialog.vue')['default']
    Uptime: typeof import('./src/components/Uptime.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
  }
}
